#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
; #Warn  ; Enable warnings to assist with detecting common errors.
SendMode Input  ; Recommended for new scripts due to its superior speed and reliability.
global dir = 0
Loop, %0%  ; For each parameter:
{
    dir := %A_Index%
}
SetWorkingDir %dir%  ; Ensures a consistent starting directory.


; Create Interface
; Generated by AutoGUI 2.5.4
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Button, x33 y32 w560 h33 gpull, PULL
Gui Add, Button, x33 y252 w228 h33 gcommit, COMMIT
Gui Add, Button, x366 y252 w228 h33 gpush, PUSH
Gui Add, Button, x33 y304 w560 h33 gcp, COMMIT AND PUSH
Gui Add, Edit, x33 y74 w560 h168 vuserinput

Gui Show, w620 h352, %dir%
Return

GuiEscape:
GuiClose:
    ExitApp

;

pull:
{
  makeAPull()
}

commit:
{
  makeACommit()
}
push:
{
  makeAPush()
}
cp:
{
  makeCP()
}

makeAPull(){
  Run, C:\Program Files\Git\bin\bash.exe, , , cmdpid
  WinWait, ahk_pid %cmdpid%
	WinActivate, ahk_pid %cmdpid%
  customUrl := chr(34) dir chr(34) . "{Enter}"
  SendInput, cd %customUrl%
  SendInput, "git pull"
}
makeACommit(){
  GuiControlGet, userinput
  Run, C:\Program Files\Git\bin\bash.exe, , , cmdpid
  WinWait, ahk_pid %cmdpid%
	WinActivate, ahk_pid %cmdpid%
  customUrl := chr(34) dir chr(34) . "{Enter}"
  SendInput, cd %customUrl%
  SendInput, chr(34) "git commit -m" . %userinput% chr(34)
}
makeAPush(){
  Run, C:\Program Files\Git\bin\bash.exe, , , cmdpid
  WinWait, ahk_pid %cmdpid%
  WinActivate, ahk_pid %cmdpid%
  customUrl := chr(34) dir chr(34) . "{Enter}"
  SendInput, cd %customUrl%
  SendInput, "git push"
}
makeCP(){
  ;GuiControlGet, userinput
  ;MsgBox, %userinput%
}
